# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53b5503a9d30931fa924cfeff844beb64d2ccc8891861503bcb0e66d8ab686f6e7dd75e9aa13ba8ebfc8af43d1021a4fe4d52e425d80d93c7cd3d345cf9b17d0

test:
  secret_key_base: 2b7f187b9de3012a226efd5d4dcec5c006e8af143d6c2b7669587d63cc07277b195b8a8d3126e11ede483b085c8f3302e075e156c11fd669f2f161d0617ba394

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
